//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caigoufentan_main
    {
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string AssignStyle { get; set; }
        public string ProofNumber { get; set; }
        public string WaitAmount { get; set; }
        public string Maker { get; set; }
        public string Permitter { get; set; }
    }
}
