//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caigoutuihuo_main
    {
        public string CustID { get; set; }
        public string AddrID { get; set; }
        public string BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string SaleClassID { get; set; }
        public string CurrID { get; set; }
        public string PriceofTax { get; set; }
        public string ExchRate { get; set; }
        public string WareID { get; set; }
        public string HasForeignTrade { get; set; }
        public string IsDeduct { get; set; }
        public int ProofNumber { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
        public string Remark { get; set; }
        public string SalesID { get; set; }
        public string Maker { get; set; }
        public string Permitter { get; set; }
        public string DepartID { get; set; }
        public string ProjectID { get; set; }
    }
}
