//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caigou
    {
        public string Qinggou { get; set; }
        public string Danjutime { get; set; }
        public Nullable<int> Danjuhaoma { get; set; }
        public string Dankuang { get; set; }
        public string Qingg { get; set; }
        public string Zhidan { get; set; }
        public string Fuhe { get; set; }
        public string Bumen { get; set; }
        public string Biaotou { get; set; }
        public string Biaowei { get; set; }
        public string Zidinyi { get; set; }
        public string Zidiner { get; set; }
        public string Beuzhu { get; set; }
        public string Jdsa { get; set; }
    }
}
