//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cangkubiao
    {
        public int CKBHao { get; set; }
        public string CKMCheng { get; set; }
        public string LXRYuan { get; set; }
        public string LXDHua { get; set; }
        public string CKDZhi { get; set; }
        public string BZu { get; set; }
    }
}
