//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chuku
    {
        public int id { get; set; }
        public string CustName { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string AddrName { get; set; }
        public string BillNO { get; set; }
        public string SaleClassName { get; set; }
        public string currname { get; set; }
        public Nullable<bool> PriceofTax { get; set; }
        public Nullable<float> ExchRate { get; set; }
        public string WareName { get; set; }
        public string HasForeignTeade { get; set; }
        public string VoucherNO { get; set; }
        public Nullable<bool> HasAutoTnv { get; set; }
        public string SalesName { get; set; }
        public string Maker { get; set; }
        public string Depayid { get; set; }
        public string Permitter { get; set; }
        public string ProectName { get; set; }
        public string Remark { get; set; }
        public string AddField1 { get; set; }
        public string AddField2 { get; set; }
        public string ABC { get; set; }
        public string BCD { get; set; }
        public string CDE { get; set; }
    }
}
