//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custbill
    {
        public string CustID { get; set; }
        public string BillDate { get; set; }
        public string Billno { get; set; }
        public string FundBillNo { get; set; }
        public string PriceOftax { get; set; }
        public string InvoiceNo { get; set; }
        public string AffirmState { get; set; }
        public string InvotypeId { get; set; }
        public string VoucherNo { get; set; }
        public string CurrID { get; set; }
        public string CVoucherNO { get; set; }
        public string ExchRate { get; set; }
        public string Salesman { get; set; }
        public string Maker { get; set; }
        public string DeptID { get; set; }
        public string ProjectID { get; set; }
        public string UDef1 { get; set; }
        public string UDef2 { get; set; }
        public string Remark { get; set; }
    }
}
