//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lbkxiangbiao
    {
        public int Number { get; set; }
        public string ProdID { get; set; }
        public string ProdName { get; set; }
        public string prodsize { get; set; }
        public string StdUnitName { get; set; }
        public Nullable<int> SumNum { get; set; }
        public Nullable<float> discountunitprice { get; set; }
        public Nullable<float> RateOfDiscount { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<float> moeny { get; set; }
        public Nullable<float> BusiTaxRate { get; set; }
        public Nullable<float> Tax { get; set; }
        public Nullable<float> taxprice { get; set; }
        public Nullable<int> batchUsed { get; set; }
        public string gift { get; set; }
        public string Invoicedetails { get; set; }
        public Nullable<int> weikaipiao { get; set; }
        public string brmack { get; set; }
        public string laiyuandanbie { get; set; }
        public string laiyuandanhao { get; set; }
        public string ABC { get; set; }
        public string BCD { get; set; }
        public string CDE { get; set; }
    }
}
