//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mxsalesquotations
    {
        public int SerNO { get; set; }
        public string ProdID { get; set; }
        public string ProdBusiTaxRate { get; set; }
        public string ProdName { get; set; }
        public string ItemRemark { get; set; }
        public string IsGift { get; set; }
        public string Discount { get; set; }
        public string TaxAmt { get; set; }
        public string UniName { get; set; }
        public string Price { get; set; }
        public string OldPrice { get; set; }
        public string Amount { get; set; }
        public string SQuantity { get; set; }
        public string sPrice { get; set; }
        public string VFTotal { get; set; }
        public string SumBTaxAmt { get; set; }
        public string SumTax { get; set; }
        public string SumAmtATax { get; set; }
        public string ProdSize { get; set; }
    }
}
