//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mxsalesorder
    {
        public int SerNO { get; set; }
        public string ProdID { get; set; }
        public string ProdSize { get; set; }
        public string SUnit { get; set; }
        public int sQuantity { get; set; }
        public string OldPrice { get; set; }
        public string Discount { get; set; }
        public string sPrice { get; set; }
        public string Amount { get; set; }
        public string VFTotal { get; set; }
        public System.DateTime PreInDate { get; set; }
        public int QtyRemain { get; set; }
        public string IsGift { get; set; }
        public string ItemRemark { get; set; }
        public string HasCombine { get; set; }
        public string TranType { get; set; }
        public string FromNO { get; set; }
        public int ManuQty { get; set; }
    }
}
