//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class otherdepots
    {
        public string BillNO { get; set; }
        public System.DateTime AdjustDate { get; set; }
        public string WareName { get; set; }
        public string VoucherNO { get; set; }
        public string SalesName { get; set; }
        public string Permitter { get; set; }
        public string BillStyleName { get; set; }
        public int SumQty { get; set; }
        public string DepartName { get; set; }
        public string Remark { get; set; }
        public string Udef1 { get; set; }
        public string Udef2 { get; set; }
        public int SerNO { get; set; }
    }
}
