//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesquotations
    {
        public string BillNO { get; set; }
        public System.DateTime BillDate { get; set; }
        public string FormalCust { get; set; }
        public string CurCurrencyName { get; set; }
        public string ExchRate { get; set; }
        public string OutAddress { get; set; }
        public string PriceOfTax { get; set; }
        public System.DateTime ValiDAte { get; set; }
        public string HeaderName { get; set; }
        public string FooterName { get; set; }
        public string PsnUerDef1 { get; set; }
        public string PsnUerDef2 { get; set; }
        public string CustMemo { get; set; }
        public string MakerName { get; set; }
        public string PermitterName { get; set; }
        public string DepartName { get; set; }
        public string SalesName { get; set; }
        public int SerNO { get; set; }
    }
}
