//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesorder
    {
        public string BillNO { get; set; }
        public System.DateTime BillDate { get; set; }
        public string CustBillNo { get; set; }
        public string BillStyleName { get; set; }
        public string CustCurrencyName { get; set; }
        public string CustMemo { get; set; }
        public string CustAddress { get; set; }
        public string SalesName { get; set; }
        public string DepartName { get; set; }
        public string ProjectName { get; set; }
        public string ExchRate { get; set; }
        public string Permitter { get; set; }
        public string Maker { get; set; }
        public string HeaderName { get; set; }
        public string FooterName { get; set; }
        public string UserDef1 { get; set; }
        public string UserDef2 { get; set; }
        public string BillStatus { get; set; }
        public string PriceOfTax { get; set; }
        public string DueToFullName { get; set; }
        public System.DateTime PrepayDay { get; set; }
        public string GatherStyle { get; set; }
        public string AccMoth { get; set; }
        public int GatherDelay { get; set; }
        public int SerNO { get; set; }
    }
}
