//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_store_io
    {
        public int Id { get; set; }
        public string Bianhao { get; set; }
        public string Wuliaomc { get; set; }
        public string Xinhao { get; set; }
        public string Mc { get; set; }
        public Nullable<int> Shul { get; set; }
        public Nullable<int> Danjia { get; set; }
        public Nullable<int> Zheshu { get; set; }
        public Nullable<int> Danj { get; set; }
        public Nullable<int> Money { get; set; }
        public string Shuil { get; set; }
        public string Shuie { get; set; }
        public string Hanshuimonet { get; set; }
        public string Yuru { get; set; }
        public Nullable<int> Weiruk { get; set; }
        public string Zengpin { get; set; }
        public string Fenlu { get; set; }
        public string Laiyuan { get; set; }
        public string Danhao { get; set; }
        public string Sj { get; set; }
    }
}
