//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_xiaoshoufapiaod
    {
        public string Kehu { get; set; }
        public string Danjuriqi { get; set; }
        public string Danjuleixing { get; set; }
        public string Danjuhaoma { get; set; }
        public string Shifouhanshui { get; set; }
        public string Fapiaohaoma { get; set; }
        public string Fapiaodizhi { get; set; }
        public string Fapiaoleixing { get; set; }
        public string Heduizhuangtai { get; set; }
        public string Bibie { get; set; }
        public string SRngzhengbianhao { get; set; }
        public Nullable<double> Huilv { get; set; }
        public string CBpingzhengbianhao { get; set; }
        public string Lanyi { get; set; }
        public string Laner { get; set; }
        public string Daochuriqi { get; set; }
        public string Daochurenyuan { get; set; }
        public string Beizhu { get; set; }
        public string Yewurenyuan { get; set; }
        public string Zhidanrenyuan { get; set; }
        public string Suoshubumen { get; set; }
        public string Fuherenyuan { get; set; }
        public string Suoshuxiangmu { get; set; }
        public string aaa { get; set; }
        public string bbb { get; set; }
    }
}
