//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yingshouchogkuandnr
    {
        public string Lanhao { get; set; }
        public string Danbie { get; set; }
        public string Yuandanriqi { get; set; }
        public string Yuandandanhao { get; set; }
        public string Fapiaohaoma { get; set; }
        public string Jiaoyiduixiang { get; set; }
        public string JiaoyiduixiangName { get; set; }
        public Nullable<int> Bumenbianhao { get; set; }
        public string Bumenmingcheng { get; set; }
        public string Yewurenyuan { get; set; }
        public string Xiangmumingchen { get; set; }
        public string Bibie { get; set; }
        public Nullable<double> Huilv { get; set; }
        public Nullable<double> Yuandanjine { get; set; }
        public Nullable<double> Xianxingyue { get; set; }
        public Nullable<double> Zherangjine { get; set; }
        public Nullable<double> Chongkuanjine { get; set; }
        public Nullable<double> Chongdijine { get; set; }
        public string qqq { get; set; }
        public string aaa { get; set; }
    }
}
