//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_yingshouchogkuand
    {
        public string Kehu { get; set; }
        public string Danjuriqi { get; set; }
        public string Jiesuanyi { get; set; }
        public string Jiesuaner { get; set; }
        public string Jiesuansan { get; set; }
        public Nullable<double> Jineyi { get; set; }
        public Nullable<double> Jineer { get; set; }
        public Nullable<double> Jinesan { get; set; }
        public Nullable<int> Danjuhao { get; set; }
        public string Bibie { get; set; }
        public Nullable<double> Huilv { get; set; }
        public Nullable<double> Zhekoulv { get; set; }
        public string YSCKleixing { get; set; }
        public string Zhongzhizhangyue { get; set; }
        public Nullable<int> Pingzhengbianhao { get; set; }
        public string Suoshubumen { get; set; }
        public string Zhidanrenyuan { get; set; }
        public string Suoshuxiangmu { get; set; }
        public string Fuherenyuan { get; set; }
        public string Zidinlanone { get; set; }
        public string Zidinlantwo { get; set; }
        public string Remark { get; set; }
        public string aaa { get; set; }
        public string bbb { get; set; }
    }
}
