//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbiao
    {
        public string SerNo { get; set; }
        public string ProsID { get; set; }
        public string ProdName { get; set; }
        public string ProdSize { get; set; }
        public string PriceOftax { get; set; }
        public string Sunit { get; set; }
        public string SQuantity { get; set; }
        public string SPrice { get; set; }
        public string Amount { get; set; }
        public string TaxRate { get; set; }
        public string TaxAmt { get; set; }
        public string RateBalanceAmt { get; set; }
        public string BalanceAmt { get; set; }
        public string LocalBalanceAmt { get; set; }
        public string TotaBalanceAmt { get; set; }
        public string ProjectID { get; set; }
        public string SourceType { get; set; }
        public string SourceBillNo { get; set; }
        public string AmountithTax { get; set; }
        public string LQty { get; set; }
        public string FromNo { get; set; }
        public string IsGift { get; set; }
        public string Remark { get; set; }
        public string rema { get; set; }
    }
}
